# Generated by Django 2.0.7 on 2018-07-08 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20)),
                ('surname', models.CharField(default='', max_length=20)),
                ('patronymic', models.CharField(default='', max_length=20)),
                ('exp', models.DateField(default='')),
                ('slug', models.SlugField(default='', max_length=20)),
                ('img', models.ImageField(default='img/doctors/default.jpg', upload_to='img/doctors/')),
            ],
        ),
        migrations.CreateModel(
            name='Doctors_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Practice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(default='img/service_icons/default.jpg', upload_to='img/service_icons/')),
                ('name', models.CharField(default='', max_length=50)),
                ('about', models.CharField(default='', max_length=5000)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='education',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to='alfa.Education'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='practice',
            field=models.ManyToManyField(default=None, related_name='doctors', to='alfa.Practice'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='services',
            field=models.ManyToManyField(default=None, related_name='doctors', to='alfa.Service'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='technologies',
            field=models.ManyToManyField(default=None, related_name='doctors', to='alfa.Technology'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='type',
            field=models.ManyToManyField(default=None, related_name='doctors', to='alfa.Doctors_type'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='doctor',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='alfa.Doctor'),
        ),
    ]
