# Generated by Django 2.0.7 on 2018-07-08 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alfa', '0002_auto_20180708_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='img',
            field=models.ImageField(default='/media/img/doctors/default.jpg', upload_to='img/doctors/'),
        ),
    ]
