# Generated by Django 2.0.7 on 2018-07-08 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alfa', '0003_auto_20180708_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='img',
            field=models.ImageField(default='/Users/nestor/Desktop/argentit/argentit/../media/img/doctors/default.jpg', upload_to='img/doctors/'),
        ),
    ]
