# Generated by Django 2.0.7 on 2018-07-09 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alfa', '0004_auto_20180708_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='img',
            field=models.ImageField(default='img/doctors/default.jpg', upload_to='img/doctors/'),
        ),
    ]
