# Generated by Django 2.0.7 on 2018-07-09 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alfa', '0005_auto_20180709_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='slug',
            field=models.SlugField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='technology',
            name='slug',
            field=models.SlugField(default='', max_length=20),
        ),
    ]
