# Generated by Django 2.0.7 on 2018-07-16 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alfa', '0007_doctor_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='text',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='technology',
            name='text',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='technology',
            name='img',
            field=models.ImageField(default='img/technologies/default.jpg', upload_to='img/technologies/'),
        ),
    ]
