# Generated by Django 2.0.7 on 2018-08-10 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alfa', '0012_auto_20180810_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
