# Generated by Django 2.0.7 on 2018-08-10 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alfa', '0013_article_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='doctor',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='alfa.Doctor'),
        ),
    ]
