# Generated by Django 2.0.7 on 2018-08-10 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alfa', '0014_auto_20180810_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='alfa.Doctor'),
        ),
    ]
