# Generated by Django 2.0.7 on 2018-08-13 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alfa', '0017_auto_20180813_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
