# Generated by Django 2.1 on 2018-08-15 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alfa', '0018_auto_20180813_1208'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=1000)),
            ],
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='img',
            new_name='photo',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='education',
        ),
        migrations.AddField(
            model_name='education',
            name='doctor',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='education', to='alfa.Doctor'),
        ),
        migrations.AddField(
            model_name='skill',
            name='doctor',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='alfa.Doctor'),
        ),
    ]
